import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/src/app/providers";

const robotoSans = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500"],
  subsets: ["latin", "cyrillic"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoSans.variable} antialiased`}>
      <body className="bg-blue-15 font-sans">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
